# ============================================
# Azure Pipelines - Integration Gateway (IGW)
# Ndërton backend (Spring Boot/Gradle) + frontend (Vite/React)
# Publikon artefakte: backend (JAR) dhe frontend (dist)
# ============================================

trigger:
  branches:
    include:
      - main

# (Opsionale) variabla të dobishme
variables:
  UI_DIR: 'ui-react'               # rruga e frontend-it
  BACKEND_ARTIFACT: 'backend'
  FRONTEND_ARTIFACT: 'frontend'

stages:
- stage: Build
  displayName: Build all
  jobs:

  # -------------------------
  # JOB 1: Backend (Gradle)
  # -------------------------
  - job: backend
    displayName: Build backend (Spring Boot)
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - checkout: self

    # ✅ Përdor Java 21 me task-un korrekt UseJava@1
    - task: UseJava@1
      displayName: 'Use Java 21'
      inputs:
        distribution: 'Microsoft'   # ose 'Temurin' / 'Zulu'
        versionSpec: '21'

    # Siguro gradle wrapper është ekzekutues
    - script: chmod +x ./gradlew
      displayName: 'chmod gradlew'

    # Build Gradle (pa testet nëse do build të shpejtë)
    - script: |
        ./gradlew clean build -x test
      displayName: 'Gradle clean build'

    # Publiko JAR-at e krijuar
    - publish: build/libs
      artifact: $(BACKEND_ARTIFACT)
      displayName: 'Publish backend artifact'

  # -------------------------
  # JOB 2: Frontend (Vite/React)
  # -------------------------
  - job: frontend
    displayName: Build frontend (ui-react)
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - checkout: self

    # ✅ Përdor Node 20
    - task: NodeTool@0
      displayName: 'Use Node 20'
      inputs:
        versionSpec: '20.x'

    # Instalime + build
    - script: |
        cd $(UI_DIR)
        npm ci
        # Nëse CI nuk e gjen lightningcss, mund të forcohet:
        # npm ls lightningcss || npm install -D lightningcss
        npm run build
      displayName: 'npm ci & build'

    # Publiko dist-in e Vite
    - publish: $(UI_DIR)/dist
      artifact: $(FRONTEND_ARTIFACT)
      displayName: 'Publish frontend artifact'
