server:
  port: ${PORT:8085}

spring:
  application:
    name: integration-gateway

# URL-të e shërbimeve (prod)
services:
  product:
    url: https://productservice.drillbi.se
    openapi: /v3/api-docs
  order:
    url: https://orderservice.drillbi.se
    openapi: /v3/api-docs
  user:
    url: https://userservice.drillbi.se
    openapi: /v3/api-docs

# Logging (mbaje vetëm nivelet)
logging:
  level:
    root: INFO
    se.moln.integrationgateway: INFO
    org.springdoc: INFO

# Konfigurimi i Springdoc / Swagger UI
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    display-operation-id: true
    tags-sorter: alpha
    operations-sorter: alpha
